repos:
  #Use Prettier to format all code files before commuit!
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "cafd5506f18eea191804850dacc0a4264772d59d"
    hooks:
      - id: prettier
